name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          path: equivalence-engine
      - uses: actions/checkout@v4
        with:
          repository: dev-centr/libequivalence
          path: libequivalence
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ldc-latest
      - name: Build
        working-directory: equivalence-engine
        run: dub build -b release
      - name: Rename binary (Windows)
        if: matrix.os == 'windows-latest'
        working-directory: equivalence-engine
        run: Move-Item bin/equivalence-engine.exe bin/equivalence-engine-${{ matrix.os }}.exe
        shell: pwsh
      - name: Rename binary (Unix)
        if: matrix.os != 'windows-latest'
        working-directory: equivalence-engine
        run: mv bin/equivalence-engine bin/equivalence-engine-${{ matrix.os }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: equivalence-engine-${{ matrix.os }}
          path: equivalence-engine/bin/equivalence-engine-${{ matrix.os }}*

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: bin
          merge-multiple: true
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*
          generate_release_notes: true

  publish-pkg:
    name: Publish Winget Package
    needs: release
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Winget Releaser
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: AMDphreak.EquivalenceEngine
          token: ${{ secrets.WINGET_TOKEN }}

  publish-homebrew:
    name: Publish Homebrew
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update Homebrew Formula
        uses: mislav/bump-homebrew-formula-action@v3
        with:
          formula-name: equivalence-engine
          homebrew-tap: AMDphreak/homebrew-tap
          download-url: https://github.com/dev-centr/equivalence-engine/releases/download/${{ github.ref_name }}/equivalence-engine-macos-latest
          commit-message: |
            equivalence-engine ${{ github.ref_name }}
        env:
          COMMITTER_TOKEN: ${{ secrets.WINGET_TOKEN }}
